services:
  expo-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: donuty-dev-app
    ports:
      - "8081:8081"
    env_file:
      - .env
    command: npx expo start
    tty: true
    stdin_open: true

    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}

    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/
            - .expo/
            - dist/
            - .git/

        - action: rebuild
          path: ./package.json

        - action: rebuild
          path: ./package-lock.json