INSERT INTO public.questions (title, correct_answer, wrong_answers, category, explanation) VALUES
-- MATH
('2 + 2 × 2 = ?', '6', ARRAY['8','4','2'], 'math', 'Mnożenie przed dodawaniem.'),
('Pierwiastek kwadratowy z 144 = ?', '12', ARRAY['14','11','13'], 'math', '12² = 144.'),
('Ile zer ma miliard?', '9', ARRAY['6','12','8'], 'math', 'Miliard = 10⁹.'),
('Ile wynosi 7! (silnia)?', '5040', ARRAY['720','40320','2520'], 'math', '7! = 7×6×5×4×3×2×1 = 5040.'),
('Ile wynosi zaokrąglone π do 2 miejsc?', '3,14', ARRAY['3,12','3,16','3,18'], 'math', 'π ≈ 3,14159…'),
('Suma kątów trójkąta to ile stopni?', '180', ARRAY['90','270','360'], 'math', 'Suma kątów wewnętrznych trójkąta = 180°.'),
-- TRAVEL
('Jakie miasto jest stolicą Japonii?', 'Tokio', ARRAY['Osaka','Kioto','Hiroszima'], 'travel', 'Tokio jest stolicą Japonii od 1869 roku.'),
('W którym kraju leży Machu Picchu?', 'Peru', ARRAY['Brazylia','Kolumbia','Ekwador'], 'travel', 'Machu Picchu leży w Andach w Peru.'),
('W którym mieście stoi Wieża Eiffla?', 'Paryż', ARRAY['Lyon','Marsylia','Nicea'], 'travel', 'Wieża Eiffla wybudowana w Paryżu w 1889 roku.'),
('Jaką walutą posługują się Japończycy?', 'Jen', ARRAY['Yuan','Won','Baht'], 'travel', 'Walutą Japonii jest jen (JPY).'),
('Na którym kontynencie leży Egipt?', 'Afryka', ARRAY['Azja','Europa','Ameryka'], 'travel', 'Egipt leży w północno-wschodniej Afryce.'),
('Jaki jest najdłuższy ocean na świecie?', 'Spokojny', ARRAY['Atlantycki','Indyjski','Arktyczny'], 'travel', 'Ocean Spokojny jest największym oceanem na Ziemi.'),
-- ENGLISH
('What is the past tense of "go"?', 'went', ARRAY['goed','gone','go'], 'english', '"Go" jest czasownikiem nieregularnym.'),
('What is the plural of "child"?', 'children', ARRAY['childs','childes','child'], 'english', 'Nieregularna liczba mnoga: child → children.'),
('Which word means "happy"?', 'joyful', ARRAY['sad','angry','tired'], 'english', 'Joyful = pełen radości.'),
('Complete: "It''s raining cats and ___"', 'dogs', ARRAY['mice','fish','birds'], 'english', 'Idiom "raining cats and dogs" = leje jak z cebra.'),
('Which article is used before "university"?', 'a', ARRAY['an','the','no article'], 'english', 'Wymowa "university" zaczyna się od /j/ (spółgłoska).'),
('What does "procrastinate" mean?', 'Odkładać na później', ARRAY['Działać szybko','Planować','Kończyć zadania'], 'english', 'Procrastinate = celowo zwlekać z zadaniem.'),
-- MEDICINE
('Ile kości ma dorosły człowiek?', '206', ARRAY['212','196','180'], 'medicine', 'Dorosły człowiek posiada 206 kości.'),
('Który narząd produkuje insulinę?', 'Trzustka', ARRAY['Wątroba','Nerki','Żołądek'], 'medicine', 'Insulina produkowana jest przez komórki beta trzustki.'),
('Co to jest BMI?', 'Wskaźnik masy ciała', ARRAY['Ciśnienie krwi','Poziom cukru','Puls'], 'medicine', 'BMI = masa (kg) / wzrost² (m²).'),
('Która witamina syntetyzowana jest przez skórę pod wpływem słońca?', 'D', ARRAY['C','B12','E'], 'medicine', 'Witamina D syntetyzowana jest w skórze pod wpływem promieniowania UV.'),
('Jakie są grupy krwi układu ABO?', 'A, B, AB, 0', ARRAY['A, B, C, D','A, B, AB, BA','1, 2, 3, 4'], 'medicine', 'Układ ABO zawiera 4 grupy: A, B, AB i 0.'),
('Prawidłowe tętno spoczynkowe dorosłego to:', '60–100 uderzeń/min', ARRAY['40–60 uderzeń/min','100–120 uderzeń/min','20–40 uderzeń/min'], 'medicine', 'Prawidłowe tętno spoczynkowe wynosi 60–100 uderzeń/min.'),
-- NATURE
('Jakie zwierzę jest największym ssakiem na świecie?', 'Płetwal błękitny', ARRAY['Słoń afrykański','Rekin wielorybi','Hipopotam'], 'nature', 'Płetwal błękitny może ważyć nawet 150 ton.'),
('Co to jest fotosynteza?', 'Wytwarzanie cukrów z CO₂ i wody przez rośliny', ARRAY['Oddychanie roślin','Rozkład materii organicznej','Zapylanie kwiatów'], 'nature', 'Fotosynteza = produkcja glukozy przy udziale światła.'),
('Ile procent powierzchni Ziemi pokrywają oceany?', '71%', ARRAY['50%','60%','80%'], 'nature', 'Oceany zajmują około 71% powierzchni naszej planety.'),
('Które drzewo żyje najdłużej?', 'Sosna oścista (Bristlecone pine)', ARRAY['Sekwoja olbrzymia','Baobab','Dąb szypułkowy'], 'nature', 'Najstarsze drzewo "Metuzalem" ma ponad 4800 lat.'),
('W jakiej warstwie atmosfery leży warstwa ozonowa?', 'Stratosfera', ARRAY['Troposfera','Mezosfera','Termosfera'], 'nature', 'Warstwa ozonowa leży w stratosferze na wys. 15–35 km.'),
('Ile gatunków mrówek żyje na Ziemi?', 'Ponad 12 000', ARRAY['Około 500','Około 2000','Ponad 50 000'], 'nature', 'Naukowcy opisali ponad 12 000 gatunków mrówek.'),
-- MOVIES
('Kto wyreżyserował "Pulp Fiction"?', 'Quentin Tarantino', ARRAY['Steven Spielberg','Martin Scorsese','Christopher Nolan'], 'movies', 'Pulp Fiction (1994) to dzieło Quentina Tarantino.'),
('W którym filmie główną rolę gra "Forrest"?', 'Forrest Gump', ARRAY['Cast Away','Philadelphia','Big'], 'movies', 'Tom Hanks zagrał Forresta Gumpa w 1994 roku.'),
('Jak nazywa się samochód z "Powrotu do przyszłości"?', 'DeLorean', ARRAY['Pontiac','Ferrari','Lamborghini'], 'movies', 'Wehikuł czasu to DeLorean DMC-12.'),
('Ile Oscarów zdobył Titanic (1997)?', '11', ARRAY['7','9','14'], 'movies', 'Titanic Camerona zdobył 11 Oscarów.'),
('W którym roku wydano "Władcę Pierścieni: Drużynę Pierścienia"?', '2001', ARRAY['1999','2003','2000'], 'movies', 'Pierwszy film Petera Jacksona z serii premierował w 2001.'),
('Która saga zaczyna się od słów "A long time ago in a galaxy far, far away..."?', 'Gwiezdne Wojny', ARRAY['Star Trek','Interstellar','Avatar'], 'movies', 'Ta kultowa fraza otwiera każdy film z sagi Star Wars.'),
-- CHEMISTRY
('Jaki symbol chemiczny ma złoto?', 'Au', ARRAY['Go','Gd','Gl'], 'chemistry', 'Au pochodzi od łacińskiego "aurum".'),
('Ile elektronów ma atom węgla?', '6', ARRAY['4','8','12'], 'chemistry', 'Węgiel (C) ma liczbę atomową 6, a więc 6 elektronów.'),
('Jaki jest wzór chemiczny wody?', 'H₂O', ARRAY['HO₂','H₂O₂','HO'], 'chemistry', 'Cząsteczka wody = 2 atomy wodoru + 1 atom tlenu.'),
('Co mierzy skala pH?', 'Kwasowość roztworu', ARRAY['Ciśnienie osmotyczne','Stężenie molarne','Temperaturę wrzenia'], 'chemistry', 'pH < 7 = kwasowe, pH = 7 = obojętne, pH > 7 = zasadowe.'),
('Ile pierwiastków liczy układ okresowy (2024)?', '118', ARRAY['108','112','120'], 'chemistry', 'Oganesson (Og, 118) to ostatni oficjalnie nazwany pierwiastek.'),
('Jak nazywa się najmniejsza jednostka materii zachowująca właściwości pierwiastka?', 'Atom', ARRAY['Elektron','Molekuła','Proton'], 'chemistry', 'Atom to podstawowa jednostka pierwiastka chemicznego.'),
-- BOOKS
('Kto napisał "Władcę Pierścieni"?', 'J.R.R. Tolkien', ARRAY['C.S. Lewis','Terry Pratchett','George R.R. Martin'], 'books', 'Tolkien wydał LOTR między 1954 a 1955 rokiem.'),
('Kto napisał "1984"?', 'George Orwell', ARRAY['Aldous Huxley','Ray Bradbury','Franz Kafka'], 'books', 'Dystopijną powieść "1984" George Orwell wydał w 1949 roku.'),
('Jak nazywa się wiedźmin z powieści Sapkowskiego?', 'Geralt z Rivii', ARRAY['Lambert','Eskel','Vesemir'], 'books', 'Geralt z Rivii to główny bohater sagi o Wiedźminie.'),
('W której książce zadebiutował Sherlock Holmes?', 'Studium w szkarłacie', ARRAY['Zbrodnia i kara','Wielki Gatsby','Proces'], 'books', 'Holmes zadebiutował w "A Study in Scarlet" (1887) Doyle''a.'),
('Kto napisał "Zbrodnię i karę"?', 'Fiodor Dostojewski', ARRAY['Lew Tołstoj','Anton Czechow','Nikołaj Gogol'], 'books', 'Dostojewski opublikował "Zbrodnię i karę" w 1866 roku.'),
('W której książce Harry Potter po raz pierwszy jedzie do Hogwartu?', 'Kamień Filozoficzny', ARRAY['Komnata Tajemnic','Więzień Azkabanu','Goblet Ognia'], 'books', 'Pierwszy tom sagi Rowling wprowadza Harry''ego do Hogwartu.'),
-- SPACE
('Ile planet liczy Układ Słoneczny?', '8', ARRAY['9','7','10'], 'space', 'Po reklasyfikacji Plutona w 2006 r. zostało 8 planet.'),
('Kto był pierwszym człowiekiem w kosmosie?', 'Jurij Gagarin', ARRAY['Buzz Aldrin','Neil Armstrong','Valentina Tiereszkowa'], 'space', 'Gagarin poleciał w kosmos 12 kwietnia 1961 roku.'),
('Jak nazywa się największa planeta Układu Słonecznego?', 'Jowisz', ARRAY['Saturn','Uran','Neptun'], 'space', 'Jowisz to gazowy olbrzym większy od wszystkich innych planet łącznie.'),
('Jak nazywa się galaktyka, w której leży Układ Słoneczny?', 'Droga Mleczna', ARRAY['Andromeda','Magellana','Triangulum'], 'space', 'Nasz Układ Słoneczny leży w galaktyce Drogi Mlecznej.'),
('Rok świetlny to:', 'Jednostka odległości', ARRAY['Czas 365 dni','1000 lat','Milion lat'], 'space', 'Rok świetlny ≈ 9,46 biliona km — to dystans, nie czas.'),
('Jaka jest odległość Ziemi od Słońca w jednostkach astronomicznych?', '1 AU', ARRAY['0,5 AU','2 AU','10 AU'], 'space', '1 AU ≈ 149,6 mln km — to definicja jednostki astronomicznej.'),
-- RELIGION
('Jak nazywa się święta księga islamu?', 'Koran', ARRAY['Tora','Biblia','Wedy'], 'religion', 'Koran jest objawioną księgą islamu.'),
('Gdzie urodził się Budda?', 'Nepal (Lumbini)', ARRAY['Indie','Tybet','Chiny'], 'religion', 'Budda (Siddhartha Gautama) urodził się w Lumbini, dzis. Nepal.'),
('Ile filarów liczy islam?', '5', ARRAY['3','6','7'], 'religion', '5 filarów islamu: wyznanie wiary, modlitwa, jałmużna, post, pielgrzymka.'),
('Jak nazywa się żydowskie święto świateł?', 'Chanuka', ARRAY['Pesach','Rosz Haszana','Jom Kipur'], 'religion', 'Chanuka trwa 8 dni i obchodzona jest w zimie.'),
('W którym mieście leży Watykan?', 'Rzym', ARRAY['Mediolan','Florencja','Neapol'], 'religion', 'Watykan to enklawa wewnątrz Rzymu.'),
('Ile głównych religii świata uważa się za "wielkie"?', '5', ARRAY['3','7','10'], 'religion', 'Za 5 wielkich uznaje się: hinduizm, buddyzm, judaizm, chrześcijaństwo, islam.'),
-- MUSIC
('Ile klawiszy ma standardowy fortepian?', '88', ARRAY['72','76','96'], 'music', 'Standardowy fortepian ma 88 klawiszy (52 białe + 36 czarne).'),
('Kto skomponował Symfonię nr 9?', 'Ludwig van Beethoven', ARRAY['Wolfgang Amadeus Mozart','Johann Sebastian Bach','Franz Schubert'], 'music', 'IX Symfonia Beethovena zawiera słynną "Odę do radości".'),
('Ile strun ma standardowa gitara?', '6', ARRAY['4','5','7'], 'music', 'Standardowa gitara akustyczna i elektryczna ma 6 strun.'),
('Co to jest "tempo" w muzyce?', 'Szybkość wykonania utworu (BPM)', ARRAY['Głośność dźwięku','Wysokość dźwięku','Barwa instrumentu'], 'music', 'Tempo wyznacza liczbę uderzeń na minutę (BPM).'),
('Jak nazywa się muzyczny utwór na 4 wykonawców?', 'Kwartet', ARRAY['Duet','Trio','Kwintet'], 'music', 'Kwartet to skład 4 wykonawców lub głosów.'),
('Jak nazywa się polska wokalistka zwana ikoną polskiej muzyki rozrywkowej?', 'Maryla Rodowicz', ARRAY['Edyta Górniak','Kayah','Kasia Kowalska'], 'music', 'Maryla Rodowicz to wieloletnia ikona polskiej muzyki.'),
-- CULINARY
('Z jakiego kraju pochodzi sushi?', 'Japonii', ARRAY['Chin','Korei','Wietnamu'], 'culinary', 'Sushi wywodzi się z japońskiej tradycji kulinarnej.'),
('Jakie zioło jest głównym składnikiem pesto alla Genovese?', 'Bazylia', ARRAY['Oregano','Rozmaryn','Mięta'], 'culinary', 'Tradycyjne pesto genueńskie bazuje na świeżej bazylii.'),
('Co to jest "roux" w kuchni?', 'Zasmażka z mąki i tłuszczu', ARRAY['Rosół wołowy','Sos pomidorowy','Marynata'], 'culinary', 'Roux to podstawa sosów i zup w kuchni francuskiej.'),
('Ile kalorii ma 1 gram białka?', '4 kcal', ARRAY['7 kcal','9 kcal','2 kcal'], 'culinary', 'Białko i węglowodany: 4 kcal/g; tłuszcze: 9 kcal/g.'),
('Co oznacza "al dente"?', 'Makaron z lekkim oporem pod zębem', ARRAY['Makaron rozgotowany','Makaron surowy','Makaron smażony'], 'culinary', '"Al dente" dosłownie znaczy "na ząb" po włosku.'),
('Jakie miasto jest ojczyzną pizzy Margherita?', 'Neapol', ARRAY['Rzym','Mediolan','Florencja'], 'culinary', 'Pizzę Margheritę stworzono w Neapolu ok. 1889 roku.'),
-- GAMES
('Ile pionków ma każdy gracz na początku szachów?', '16', ARRAY['8','12','20'], 'games', 'W szachach każdy gracz startuje z 16 figurami.'),
('Jak nazywa się brat Maria w grach Nintendo?', 'Luigi', ARRAY['Wario','Waluigi','Toad'], 'games', 'Luigi to zielony brat Maria, towarzysz wielu przygód.'),
('W którym roku ukazała się pełna wersja Minecrafta?', '2011', ARRAY['2009','2013','2015'], 'games', 'Minecraft 1.0 ukazał się 18 listopada 2011.'),
('Jak nazywa się główny bohater serii The Legend of Zelda?', 'Link', ARRAY['Zelda','Ganon','Sheik'], 'games', 'Bohaterem jest Link, choć seria nosi imię księżniczki Zeldy.'),
('Ile pól ma standardowa szachownica?', '64', ARRAY['36','81','100'], 'games', 'Szachownica to siatka 8×8 = 64 pola.'),
('Ile graczy startuje w jednej rozgrywce PUBG?', '100', ARRAY['50','64','150'], 'games', 'PUBG wysadza 100 graczy na mapę, ostatni żywy wygrywa.'),
-- HISTORY
('W którym roku wybuchła II Wojna Światowa?', '1939', ARRAY['1937','1941','1914'], 'history', 'II WŚ rozpoczęła się 1 września 1939 r. atakiem Niemiec na Polskę.'),
('Kto był pierwszym prezydentem USA?', 'George Washington', ARRAY['Abraham Lincoln','Thomas Jefferson','Benjamin Franklin'], 'history', 'Waszyngton objął urząd prezydenta 30 kwietnia 1789 roku.'),
('W którym roku upadł mur berliński?', '1989', ARRAY['1991','1987','1985'], 'history', 'Mur berliński padł w nocy z 9 na 10 listopada 1989 roku.'),
('Jak nazywał się statek-flagowy Kolumba podczas rejsu 1492?', 'Santa María', ARRAY['Pinta','Niña','Vizcaína'], 'history', 'Kolumb był kapitanem Santa Maríi podczas historycznego rejsu.'),
('Która bitwa zakończyła epopeje napoleońskie?', 'Waterloo (1815)', ARRAY['Trafalgar (1805)','Lipsk (1813)','Austerlitz (1805)'], 'history', 'Bitwa pod Waterloo 18 czerwca 1815 zakończyła rządy Napoleona.'),
('W którym wieku żył Napoleon Bonaparte?', 'XVIII–XIX w.', ARRAY['XVII w.','XVI–XVII w.','XIX–XX w.'], 'history', 'Napoleon żył w latach 1769–1821.'),
-- FLAGS
('Ile gwiazd ma flaga USA?', '50', ARRAY['48','52','49'], 'flags', '50 gwiazd reprezentuje 50 stanów, 13 pasów — pierwotne kolonie.'),
('Jakie kolory ma flaga Polski?', 'Biały i czerwony', ARRAY['Biały i niebieski','Czerwony i żółty','Biały, czerwony i niebieski'], 'flags', 'Flaga Polski: biały pasek u góry, czerwony u dołu.'),
('Który kraj ma na fladze liść klonu?', 'Kanada', ARRAY['Australia','Nowa Zelandia','Irlandia'], 'flags', 'Czerwony liść klonu widnieje na środku białego pasa flagi Kanady.'),
('Ile pasów i jakie kolory ma flaga Niemiec?', '3 pasy: czarny, czerwony, złoty', ARRAY['2 pasy: czarny i złoty','4 pasy','5 pasów'], 'flags', 'Flaga Niemiec składa się z 3 poziomych pasów.'),
('Jaki symbol widnieje na fladze Japonii?', 'Czerwone koło (słońce)', ARRAY['Chryzantema','Góra Fuji','Ryba'], 'flags', 'Czerwone koło symbolizuje wschodzące słońce — Nihonmaru.'),
('Który kraj ma trójkąt na fladze?', 'Kuba', ARRAY['Brazylia','Meksyk','Kolumbia'], 'flags', 'Flaga Kuby ma czerwony trójkąt przy maszcie.'),
-- COUNTRIES
('Jakim językiem mówi się w Brazylii?', 'Portugalskim', ARRAY['Hiszpańskim','Brazylijskim','Angielskim'], 'countries', 'Brazylia była kolonią Португалии — język urzędowy to portugalski.'),
('Który kraj ma największą powierzchnię na świecie?', 'Rosja', ARRAY['Kanada','USA','Chiny'], 'countries', 'Rosja zajmuje ok. 17 mln km² — to największy kraj świata.'),
('Ile krajów należy do Unii Europejskiej (2024)?', '27', ARRAY['28','25','30'], 'countries', 'Po Brexicie w 2020 UE liczy 27 państw członkowskich.'),
('Jaka jest stolica Australii?', 'Canberra', ARRAY['Sydney','Melbourne','Brisbane'], 'countries', 'Wielu myli stolicę — to Canberra, nie Sydney.'),
('W którym kraju leży Kilimandżaro?', 'Tanzania', ARRAY['Kenia','Uganda','Etiopia'], 'countries', 'Kilimandżaro (5895 m n.p.m.) leży w Tanzanii.'),
('Który kraj jest największym producentem ropy naftowej?', 'Arabia Saudyjska', ARRAY['USA','Rosja','Irak'], 'countries', 'Arabia Saudyjska produkuje ok. 12% światowej ropy.'),
-- IT
('Co oznacza skrót CPU?', 'Central Processing Unit', ARRAY['Computer Processing Unit','Core Power Unit','Control Processing Utility'], 'IT', 'CPU to jednostka centralna — główny procesor komputera.'),
('W jakim języku napisane jest jądro Linuxa?', 'C', ARRAY['C++','Assembly','Rust'], 'IT', 'Jądro Linuxa napisano głównie w C (z elementami Assemblera).'),
('Co oznacza HTTP?', 'HyperText Transfer Protocol', ARRAY['High Transfer Text Protocol','Hyper Text Technical Protocol','Host Transfer Type Protocol'], 'IT', 'HTTP to protokół przesyłu hipertekstu w sieci WWW.'),
('Ile bitów ma jeden bajt?', '8', ARRAY['4','16','10'], 'IT', '1 bajt = 8 bitów — podstawowa jednostka informacji.'),
('Co to jest SQL?', 'Język zapytań do baz danych', ARRAY['Język programowania obiektowego','System operacyjny','Protokół sieciowy'], 'IT', 'SQL (Structured Query Language) służy do zarządzania bazami danych.'),
('W którym roku powstał Python?', '1991', ARRAY['1985','1995','2000'], 'IT', 'Guido van Rossum opublikował pierwszą wersję Pythona w 1991 r.'),
-- USELESS_FACTS
('Ile razy mruga człowiek na minutę (średnio)?', '15–20', ARRAY['5–10','30–40','1–5'], 'useless_facts', 'Mrugamy ok. 15–20 razy na minutę, czyli ~10 mln razy w roku.'),
('Jaki kolor języka ma żyrafa?', 'Ciemnofioletowy/czarny', ARRAY['Różowy','Czerwony','Brązowy'], 'useless_facts', 'Ciemny barwnik chroni język żyrafy przed oparzeniem słonecznym.'),
('Ile serc ma ośmiornica?', '3', ARRAY['1','2','4'], 'useless_facts', 'Ośmiornica ma 3 serca — dwa skrzelowe i jedno główne.'),
('Ile nóg ma pająk?', '8', ARRAY['6','10','12'], 'useless_facts', 'Pająki są pajęczakami — mają 8 nóg (owady mają 6).'),
('Jak długo złota rybka pamięta?', 'Co najmniej kilka miesięcy', ARRAY['3 sekundy','1 minutę','1 dzień'], 'useless_facts', 'Mit 3 sekund jest fałszywy — złota rybka pamięta nawet kilka miesięcy.'),
('Który kraj jest największym producentem czekolady na świecie?', 'Niemcy', ARRAY['Szwajcaria','Belgia','USA'], 'useless_facts', 'Niemcy są liderem produkcji, choć Szwajcaria kojarzona jest z jej jakością.');
